version: '3.7'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=test_graph
      - POSTGRES_USER=test_graph_user
      - POSTGRES_PASSWORD=12345678
    ports:
      - "6543:5432"
  backend:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "python3 backend_prestart.py && alembic upgrade head && uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 80"
    volumes:
      - ./:/backend/
    ports:
      - 80:80